### ISSUE TITLE
Grease-monkey Script

### ISSUE THREAD

**Issue by iwalton3** [derek-zhou/airss#1]
I made a user script here that can be used to solve the CORS issue for people who would prefer not to use more extensions or disable CORS.

https://greasyfork.org/en/scripts/433329-airss-cors-bypass

**Comment by derek-zhou** [comment]
Nice. I don't use greasemonkey myself, but feel free to send a PR to update the readme to mention this.

**Comment by derek-zhou** [comment]
Merged, thanks!

**Comment by iwalton3** [comment]
Also just thinking, but it really should be made abundantly clear that if a user disables CORS or installs one of those extensions without setting it to only run on airss, they are opening themselves up to account takeovers and malicious actions from web sites.

The Greasemonkey script does have the advantage of being a "single click" solution that doesn't default to this unsafe state.

**Comment by derek-zhou** [comment]
Newbies should just use the proxy option. Anything else is too complicated. And it is probably the only viable option for mobile. I can update the github readme with the risk associated with wide-open CORS.

At least on latest Firefox, the cookies etc are silo'ed to root domain names. So even if CORS is totally disabled, a malicious site cannot do cross site access that requires authentication. So it is also not as bad as one would think.
