### ISSUE TITLE
All feeds are invalid

### ISSUE THREAD

**Issue by v1nc** [derek-zhou/airss#3]
It says `The feed xyz is not valid` for all links I tried.
For example:
- https://lwn.net/headlines/newrss
- https://news.ycombinator.com/rss
- https://www.theguardian.com/uk/rss

**Comment by derek-zhou** [comment]
It is the CORS thing. Please read the readme in this project. I am going to make it more obvious from the greeting screen.

**Comment by v1nc** [comment]
> It is the CORS thing. Please read the readme in this project. I am going to make it more obvious from the greeting screen.

Maybe you could add a more exact error message.

**Comment by derek-zhou** [comment]
Did you get your feeds? It is not that I don't want to provide detailed error message; for CORS errors, the program only gets a `TypeError`. In other cases, the error message from the various browsers could be more confusing. A peek in the javascript console will show you what is wrong.
